SET SCHEMA PUBLIC
CREATE TABLE MENU (MENU_IDX NUMERIC(20) PRIMARY KEY, MENU_NAME VARCHAR(100))

INSERT INTO MENU VALUES (0, '비회원')

INSERT INTO MENU VALUES (1, '회원')

INSERT INTO MENU VALUES (2, '관리자')
