
CREATE TABLE USER_AUTHORITY
(
    USERNAME  VARCHAR(20) PRIMARY KEY ,
    AUTHORITY VARCHAR(20) DEFAULT 'NORMAL'
);

INSERT INTO USER_AUTHORITY VALUES ('admin', 'ADMIN');
INSERT INTO USER_AUTHORITY VALUES ('아무개1', 'MEMBER');
INSERT INTO USER_AUTHORITY VALUES ('아무개2', 'MEMBER');
INSERT INTO USER_AUTHORITY VALUES ('아무개3', 'MEMBER');
INSERT INTO USER_AUTHORITY VALUES ('아무개4', 'MEMBER');
INSERT INTO USER_AUTHORITY VALUES ('아무개5', 'MEMBER');
INSERT INTO USER_AUTHORITY VALUES ('아무개6', 'MEMBER');
INSERT INTO USER_AUTHORITY VALUES ('아무개7', 'MEMBER');
INSERT INTO USER_AUTHORITY VALUES ('아무개8', 'MEMBER');
INSERT INTO USER_AUTHORITY VALUES ('아무개9', 'MEMBER');
INSERT INTO USER_AUTHORITY VALUES ('아무개10', 'MEMBER');
INSERT INTO USER_AUTHORITY VALUES ('아무개11', 'MEMBER');